using System.Threading;
using System.Threading.Tasks;
using Luno.SDK.Trading;

namespace Luno.SDK;

/// <summary>
/// Client for managing high-fidelity order lifecycles on the Luno exchange.
/// </summary>
public interface ILunoTradingClient
{
    /// <summary>
    /// Asynchronously posts a new limit order to Luno, reconciling 409 Idempotency Conflicts natively.
    /// </summary>
    /// <param name="parameters">The parameters defining the limit order.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>A <see cref="Task"/> returning the <see cref="OrderReference"/> from the exchange.</returns>
    Task<OrderReference> PostLimitOrderAsync(LimitOrderParameters parameters, CancellationToken ct = default);

    /// <summary>
    /// Asynchronously stops an active order using the Luno standard Order ID.
    /// </summary>
    /// <param name="orderId">The unique Order ID generated by the exchange.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>A boolean indicating if the stop request was accepted.</returns>
    Task<bool> StopOrderAsync(string orderId, CancellationToken ct = default);

    /// <summary>
    /// Asynchronously retrieves detailed information about an order.
    /// </summary>
    /// <param name="orderId">Optional unique Order ID.</param>
    /// <param name="clientOrderId">Optional Client Order ID.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>Detailed order information.</returns>
    /// <exception cref="LunoValidationException">Thrown if neither ID is provided.</exception>
    Task<Order> GetOrderAsync(string? orderId = null, string? clientOrderId = null, CancellationToken ct = default);
}
