using System.Threading;
using System.Threading.Tasks;
using Luno.SDK.Trading;

namespace Luno.SDK;

/// <summary>
/// Client for managing high-fidelity order lifecycles on the Luno exchange.
/// </summary>
public interface ILunoTradingClient
{
    /// <summary>
    /// Asynchronously posts a new limit order to Luno, reconciling 409 Idempotency Conflicts natively.
    /// </summary>
    /// <param name="parameters">The parameters defining the limit order.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>A <see cref="Task"/> returning the <see cref="OrderReference"/> from the exchange.</returns>
    Task<OrderReference> PostLimitOrderAsync(LimitOrderParameters parameters, CancellationToken ct = default);

    /// <summary>
    /// Asynchronously stops an active order using the Luno standard Order ID.
    /// </summary>
    /// <param name="orderId">The unique Order ID generated by the exchange.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>A boolean indicating success.</returns>
    Task<bool> StopOrderAsync(string orderId, CancellationToken ct = default);

    /// <summary>
    /// Asynchronously looks up and stops an active order using the explicit Client Order ID.
    /// </summary>
    /// <param name="clientOrderId">The client-defined deduplication ID.</param>
    /// <param name="ct">A <see cref="CancellationToken"/> to observe.</param>
    /// <returns>A boolean indicating success.</returns>
    Task<bool> StopOrderByClientOrderIdAsync(string clientOrderId, CancellationToken ct = default);
}
