// <auto-generated />
#nullable enable
using System.Collections.Frozen;
using Microsoft.Kiota.Abstractions;

namespace Luno.SDK.Infrastructure.Authentication;

/// <summary>
/// Provides a high-performance lookup for permission requirements derived from the Luno API Specification.
/// This file is auto-generated by scripts/patch-spec.js. DO NOT EDIT MANUALLY.
/// </summary>
internal static class LunoSecurityMetadata
{
    private static readonly FrozenDictionary<string, string> _permissions = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        { "DELETE /api/1/beneficiaries/{id}", "Perm_W_Beneficiaries" },
        { "DELETE /api/1/withdrawals/{id}", "Perm_W_Withdrawals" },
        { "GET /api/1/accounts/{id}/pending", "Perm_R_Transactions" },
        { "GET /api/1/accounts/{id}/transactions", "Perm_R_Transactions" },
        { "GET /api/1/balance", "Perm_R_Balance" },
        { "GET /api/1/beneficiaries", "Perm_R_Beneficiaries" },
        { "GET /api/1/fee_info", "Perm_R_Orders" },
        { "GET /api/1/funding_address", "Perm_R_Addresses" },
        { "GET /api/1/listorders", "Perm_R_Orders" },
        { "GET /api/1/listtrades", "Perm_R_Orders" },
        { "GET /api/1/orders/{id}", "Perm_R_Orders" },
        { "GET /api/1/withdrawals", "Perm_R_Withdrawals" },
        { "GET /api/1/withdrawals/{id}", "Perm_R_Withdrawals" },
        { "GET /api/exchange/1/transfers", "Perm_R_Transfers" },
        { "GET /api/exchange/2/listorders", "Perm_R_Orders" },
        { "GET /api/exchange/2/orders/{id}", "Perm_R_Orders" },
        { "GET /api/exchange/3/order", "Perm_R_Orders" },
        { "POST /api/1/accounts", "Perm_W_Addresses" },
        { "POST /api/1/address/validate", "Perm_W_Send" },
        { "POST /api/1/beneficiaries", "Perm_W_Beneficiaries" },
        { "POST /api/1/funding_address", "Perm_W_Addresses" },
        { "POST /api/1/marketorder", "Perm_W_Orders" },
        { "POST /api/1/postorder", "Perm_W_Orders" },
        { "POST /api/1/send", "Perm_W_Send" },
        { "POST /api/1/stoporder", "Perm_W_Orders" },
        { "POST /api/1/withdrawals", "Perm_W_Withdrawals" },
        { "PUT /api/1/accounts/{id}/name", "Perm_W_Addresses" },
    }
    .ToFrozenDictionary();

    /// <summary>
    /// Gets the required Luno permission for a given request.
    /// </summary>
    /// <param name="method">The HTTP method.</param>
    /// <param name="urlTemplate">The Kiota URL template (e.g., "{+baseurl}/api/1/balance").</param>
    /// <returns>The permission string (e.g., "Perm_R_Balance") if auth is required; otherwise, null.</returns>
    public static string? GetRequiredPermission(string method, string urlTemplate)
    {
        var path = NormalizeTemplate(urlTemplate);
        if (string.IsNullOrEmpty(path)) return null;

        var key = $"{method.ToUpperInvariant()} {path}";

        return _permissions.TryGetValue(key, out var permission) ? permission : null;
    }

    private static string NormalizeTemplate(string template)
    {
        if (string.IsNullOrEmpty(template)) return string.Empty;

        // 1. Strip the baseurl prefix
        var path = template.Replace("{+baseurl}", "");

        // 2. Locate the start of query parameters (supports both literal '?' and RFC 6570 '{?' used by Kiota)
        int queryIndex = path.IndexOf('?');
        int templateQueryIndex = path.IndexOf("{?");
        
        int firstIndex = -1;
        if (queryIndex != -1 && templateQueryIndex != -1) firstIndex = Math.Min(queryIndex, templateQueryIndex);
        else if (queryIndex != -1) firstIndex = queryIndex;
        else if (templateQueryIndex != -1) firstIndex = templateQueryIndex;

        if (firstIndex != -1)
        {
            path = path.Substring(0, firstIndex);
        }

        // 3. Normalize path: remove trailing slash and ensure it begins with one
        path = path.TrimEnd('/');
        if (!path.StartsWith("/")) path = "/" + path;

        return path;
    }
}
